services:
  cuda:
    build:
      context: .
      dockerfile: Dockerfile_DevEnv
    image: llp-cuda:custom
    container_name: llp-cuda
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    restart: unless-stopped